In [1]:
import pandas as pd

In [2]:
df_book_vectors = pd.read_json("Book_vectors.json")
df_book_vectors.head()

,Book-Title,254,2276,2766,2977,3363,4017,4385,6251,6323,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
0,10 Lb. Penalty,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0.0,0,0,0,0,0,0,0,0.0
1,16 Lighthouse Road,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0.0,0,0,0,0,0,0,0,0.0
2,1984,9.0,0,0,0,0,0,0,0.0,0.0,...,10,0.0,0,0,0,0,0,0,0,0.0
3,1st to Die: A Novel,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0.0,0,0,0,0,0,0,0,0.0
4,2010: Odyssey Two,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0.0,0,0,0,0,0,0,0,0.0

In [3]:
df_master = pd.read_csv("datasets/Books.csv")
df_master.head()

C:\Users\vikas\AppData\Local\Temp\ipykernel_22888\3651517282.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_master = pd.read_csv("datasets/Books.csv")

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
df_merged = pd.merge(df_book_vectors, df_master, on="Book-Title",how="inner")
df_merged.head()

,Book-Title,254,2276,2766,2977,3363,4017,4385,6251,6323,...,277427,277639,278418,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,10 Lb. Penalty,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0399143025,Dick Francis,1997,Putnam Pub Group,http://images.amazon.com/images/P/0399143025.0...,http://images.amazon.com/images/P/0399143025.0...,http://images.amazon.com/images/P/0399143025.0...
1,10 Lb. Penalty,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0515123471,Dick Francis,1998,Jove Books,http://images.amazon.com/images/P/0515123471.0...,http://images.amazon.com/images/P/0515123471.0...,http://images.amazon.com/images/P/0515123471.0...
2,16 Lighthouse Road,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,1551668300,Debbie Macomber,2001,Mira,http://images.amazon.com/images/P/1551668300.0...,http://images.amazon.com/images/P/1551668300.0...,http://images.amazon.com/images/P/1551668300.0...
3,1984,9.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0451524934,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...
4,1984,9.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0451519841,George Orwell,1980,New Amer Library,http://images.amazon.com/images/P/0451519841.0...,http://images.amazon.com/images/P/0451519841.0...,http://images.amazon.com/images/P/0451519841.0...

In [9]:
df_merged.to_json("Master_Book_Vectors.json")

In [6]:
df_merged.drop_duplicates(subset="Book-Title", inplace=True)

In [8]:
df_merged.head(100)

,Book-Title,254,2276,2766,2977,3363,4017,4385,6251,6323,...,277427,277639,278418,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,10 Lb. Penalty,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0399143025,Dick Francis,1997,Putnam Pub Group,http://images.amazon.com/images/P/0399143025.0...,http://images.amazon.com/images/P/0399143025.0...,http://images.amazon.com/images/P/0399143025.0...
2,16 Lighthouse Road,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,1551668300,Debbie Macomber,2001,Mira,http://images.amazon.com/images/P/1551668300.0...,http://images.amazon.com/images/P/1551668300.0...,http://images.amazon.com/images/P/1551668300.0...
3,1984,9.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0451524934,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...
12,1st to Die: A Novel,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0446610038,James Patterson,2002,Warner Vision,http://images.amazon.com/images/P/0446610038.0...,http://images.amazon.com/images/P/0446610038.0...,http://images.amazon.com/images/P/0446610038.0...
14,2010: Odyssey Two,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0345303067,Arthur C. Clarke,1984,Del Rey Books,http://images.amazon.com/images/P/0345303067.0...,http://images.amazon.com/images/P/0345303067.0...,http://images.amazon.com/images/P/0345303067.0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,A Yellow Raft in Blue Water,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0446387878,Michael Dorris,1998,Warner Books,http://images.amazon.com/images/P/0446387878.0...,http://images.amazon.com/images/P/0446387878.0...,http://images.amazon.com/images/P/0446387878.0...
235,AGE OF INNOCENCE (MOVIE TIE-IN),0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,002026478X,Edith Wharton,1993,Scribner,http://images.amazon.com/images/P/002026478X.0...,http://images.amazon.com/images/P/002026478X.0...,http://images.amazon.com/images/P/002026478X.0...
236,ANGELA'S ASHES,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0684874350,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...
238,Abduction,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,042517736X,Robin Cook,2000,Berkley Publishing Group,http://images.amazon.com/images/P/042517736X.0...,http://images.amazon.com/images/P/042517736X.0...,http://images.amazon.com/images/P/042517736X.0...
242,About Face,0.0,0,0,0,0,0,0,0.0,0.0,...,0,0,0.0,0821770209,Fern Michaels,2003,Zebra Books,http://images.amazon.com/images/P/0821770209.0...,http://images.amazon.com/images/P/0821770209.0...,http://images.amazon.com/images/P/0821770209.0...